settings:
  title: 'AS215520 Status Page'
  url: 'https://status-page.as215520.net' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: anycast-node # unique identifier
    name: Anycast Node
    url: 'http://[2a0f:85c1:368::b00b]' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    linkable: false # allows the title to be a link, default=true
    followRedirect: true
  - id: anycast-uk-london # unique identifier
    name: Anycast Network - London, UK
    url: 'https://gblonv-bgp01.as215520.net' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    linkable: false # allows the title to be a link, default=true
    followRedirect: true

  - id: anycast-ca-toronto
    name: Anycast Network - Toronto, CA
    url: 'https://catorv-bgp01.as215520.net/'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
    followRedirect: true

  - id: as215520-net
    name: AS215520
    url: 'https://as215520.net/'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: google
    name: Google
    url: 'https://google.com/'
    method: GET
    expectStatus: 200
    followRedirect: true
